# Generated by Django 5.0.1 on 2024-02-03 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address', models.AutoField(primary_key=True, serialize=False)),
                ('address_region', models.CharField(max_length=30)),
                ('address_locality', models.CharField(max_length=30)),
                ('address_street', models.CharField(max_length=30)),
                ('address_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id_donation', models.AutoField(primary_key=True, serialize=False)),
                ('donation_type', models.CharField(max_length=30)),
                ('donation_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id_Donor', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=30)),
                ('donor_rut', models.CharField(max_length=30)),
                ('donor_email', models.CharField(max_length=30)),
                ('donor_phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id_center', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=30)),
                ('center_available', models.BooleanField()),
                ('center_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_acopio.address')),
                ('center_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_acopio.donation')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_acopio.donor'),
        ),
    ]
