# Generated by Django 5.0.1 on 2024-02-04 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acopio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='center_address',
        ),
        migrations.RemoveField(
            model_name='center',
            name='center_classification',
        ),
        migrations.AddField(
            model_name='address',
            name='center_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_acopio.center'),
        ),
        migrations.AddField(
            model_name='donation',
            name='center_donation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_acopio.center'),
        ),
    ]
